import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { isSignedIn } = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#353535] to-[#2e2e2e]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "></div>
        <h1 className="text-2xl text-white">My t3-stack playground app</h1>
        <div className="text-white">
          {!isSignedIn && <SignInButton />}
          {isSignedIn && <SignOutButton />}
        </div>
      </main>
    </>
  );
}
