import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/Loading";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <div>{user.fullName}</div>
      <input
        className="grow bg-transparent text-white outline-none"
        placeholder="Type some emoji"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div
      className="flex flex-col gap-3 border-b-2 border-cyan-100 p-8"
      key={post.id}
    >
      <div className="flex gap-1">
        <span>{author.username}</span>
        <span>{`- ${dayjs(post.createdAt).fromNow()}`}</span>
      </div>
      <span>{post.content}</span>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: PostLoading } = api.posts.getAll.useQuery();

  if (PostLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong</div>;

  return (
    <div>
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

export default function Home() {
  const { isSignedIn } = useUser();

  //start fetching asap
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="layout h-screen border-2 border-cyan-200">
          <div className="border-b-2 border-cyan-200">
            <div className="p-8 text-xl">
              {!isSignedIn && <SignInButton />}
              {isSignedIn && <CreatePostWizard />}
            </div>
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
